Title =  "坚持做有趣的事，让生活简单快乐！"
BaseUrl = "https://qz757.github.io/"

DefaultContentLanguage = "zh-cn"
LanguageCode = "zh-CN"

Theme =  "hugo-theme-next"

MetaDataFormat =  "toml"

PaginatePath =  "p"
Paginate = 5

DisablePathToLower =  false

PreserveTaxonomyNames = false

PygmentsStyle = "emacs"
pygmentsCodefences = true
pygmentsCodefencesGuessSyntax = true

enableRobotsTXT = true
enableEmoji = true
hasCJKLanguage = true

timeout = 100000
ignoreErrors = ["error-remote-getjson"]

[outputFormats]
  [outputFormats.SearchIndex]
    mediaType = "application/xml"
    baseName = "searchindex"
    isPlainText = true
    notAlternative = true

[outputs]
  home = ["HTML", "SearchIndex"]

[minify]
  disableCSS = false
  disableHTML = false
  disableJS = false
  disableJSON = false
  disableSVG = false
  disableXML = false
  minifyOutput = true

## 让Markdown支持写HTML语法
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true