[[Main]]
  Name = "Home"
  Pre = "home"
  URL = "/"
  Weight = 1
[[Main]]
  Name = "Archive"
  Pre = "archive"
  URL = "post"
  Weight = 2
[[Main]]
  Name = "Categories"
  Pre = "archive"
  URL = "categories"
  Weight = 3
[[Main]]
  Name = "Tags"
  Pre = "tags"
  URL = "tags"
  Weight = 4
[[Main]]
  Name = "About"
  Pre = "user"
  URL = "about.html"
  Weight = 6