Description = "Ethan's Blog"
Keywords =  "Blog, Software, Thinking, Read, Note，Manager"
Subtitle = "Insist on doing fun things and make life simple and happy."
AuthorImg = "/img/head.jpeg"
AuthorName = ""
Introduce = "Insist on doing fun things and make life simple and happy."
DateFormat = "2006/01/02"
YearFormat = "2006Y"
MonthFormat = "01/02"


[[Socials]]
  Name = "GitHub"
  Icon = "github"
  URL = "https://github.com/qz757/"

[[Socials]]
  Name = "jianshu"
  Icon = "globe"
  URL = "https://www.jianshu.com/u/e8ca66cdb1d7"