language: node_js
node_js: stable

# S: Build Lifecycle
install:
  - npm install

#before_script:
 # - npm install -g gulp

script:
  - hexo g

after_script:
  - mkdir newpublic
  - git config user.name "ci"
  - git config user.email "qz757@sina.com"
  - cd newpublic
  - git clone -b master "https://${GH_TOKEN}@${GH_REF}"
  - cp -rf ../public/* ./
  - git add -A
  - git commit -m "CI Update"
  #- git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
  - git push origin master
# E: Build LifeCycle

branches:
  only:
    - hexo
env:
 global:
   - GH_REF: github.com/qz757/qz757.github.com.git
